### ISSUE TITLE
requesting language-wise publication statistics

### ISSUE THREAD

**Issue by suralk** [neubig/globalutility#1]
Dear Graham
Your paper mentions that you calculated the number of research papers that mentions each language. Can you please point me to that file in this repository?

Regards
Surangika

**Comment by neubig** [comment]
Thanks for the interest! The data should be here: https://github.com/neubig/globalutility/tree/main/area-classifier/data

**Comment by suralk** [comment]
Thanks for pointing to the data. However, we noticed that the data only considers main conferences in anthology, but omits other conferences and workshops. Do you have this additional data as well? If not, which piece of code can be used to generate this data?

**Comment by antonisa** [comment]
We did only consider the main conferences for our work. I'll add the code and readme to guide you on replicating this on other conferences/papers.

**Comment by suralk** [comment]
> We did only consider the main conferences for our work. I'll add the code and readme to guide you on replicating this on other conferences/papers.

Many thanks once again for the prompt response.  By any chance would you be able to release the code within this week? Sorry to push you, but we are racing against time for a very critical deadline. As if by luck, we came across this repo.

**Comment by antonisa** [comment]
I will try to do this today, but it's the start of the semester at my university so I'm super busy too!

**Comment by suralk** [comment]
that is totally fine :) whenever you have time, please upload.

**Comment by antonisa** [comment]
Pushed! Please see here: https://github.com/neubig/globalutility/tree/main/anthology_exp

I'm closing this for now but feel free to re-open it if you have any additional questions.

**Comment by suralk** [comment]
Yes, we managed to use your code and extract the data. Thank you. Btw, came across this just today. You would find it useful: https://twitter.com/shauryr/status/1566780472419848197?s=20&t=An0q6EYYnThGxHZoAWpNhQ
